### ISSUE TITLE
build failure 

### ISSUE THREAD

**Issue by AshwinKrishn** [kernkonzept/ham#4]
~/ham$ make 
pp -vvv  -p -o ham.par ham | grep -E "adding\s+/" | cut -f 4 -d' ' | xargs echo ham.par: >.ham.d
/bin/sh: 1: pp: not found
./par-archive -b -Oham.pl ham.par
Cannot find 'ham.par': No such file or directory at ./par-archive line 468.
Makefile:15: recipe for target 'ham.pl' failed
make: *** [ham.pl] Error 2

**Comment by alacko** [comment]
For what you're trying to do you need to install the 'pp' program, which is available in Debian/Ubuntu via the libpar-packer-perl package.

**Comment by alexwarg** [comment]
However, you can use ham wihtout running make. Simply call the ham script in the top level directory. Using parpacker is not needed and might be considered an experiment.

**Comment by AshwinKrishn** [comment]
Thank you. 
I also have an additional request. I tried the tutorial from fiasco and l4re website. The kernel does not seem to boot. Can you kindly point out the best resource for running l4re ? Some working examples ? 

Thank you.

**Comment by icedieler** [comment]
Hi,
I assume you are trying to follow the [Linux VM tutorial](https://github.com/kernkonzept/manifest/wiki/LinuxVM)? Then could you please open a dedicated issue in e.g. the [manifest project](https://github.com/kernkonzept/manifest)?
Thanks!

**Comment by icedieler** [comment]
The original issue seems to be solved. Thus closing it.
